###################################
#####  MystcraftUtils Config  #####
###################################

# World that players spawn in. Most often the overworld
spawnWorld: "LandOfWarfare"

# Dimensions that players cannot claim and will not be auto-teleported in
blacklistedDimensions:
 - "Overworld"
 - "Overworld_the_End"
 - "LandOfWarfare"

# Whether players will get auto-teleported to spawn on logout
autoSpawnLogin: false
autoSpawnLogout: true

###################################
#####         Events          #####
###################################

# Called when someone claims a dimension
claimcommands:
  - "/rg -w %dimension% addowner __global__ %player%"
  - "/rg -w %dimension% flag __global__ entry DENY"
  - "/rg -w %dimension% flag __global__ entry-deny-message This dimension has been claimed by %player%"

# Called when an owner is added to a dimension
addownercommands:
  - "/rg -w %dimension% addowner __global__ %player%"

# Called when an owner is removed from a dimension
removeownercommands:
  - "/rg -w %dimension% removeowner __global__ %player%"

# Called when a member is added to a dimension
addmembercommands:
  - "/rg -w %dimension% addmember __global__ %player%"

# Called when a member is removed from a dimension
removemembercommands:
  - "/rg -w %dimension% removemember __global__ %player%"

###################################
#####        Messages         #####
###################################

noPermission: "&cYou don't have permission"

idMessage: "&7Dimension name: %dimension%"
claimMessage: "&7You have successfully claimed dimension %dimension%"
deleteMessage: "&7Dimension %dimension% has been deleted"
spawnMessage: "&7You have been sent to spawn from %dimension%"
spawnCancelledMessage: "&7Blacklisted dimension. Sending to spawn cancelled"
reloadMessage: "&7Config has been reloaded"

sendOwnerAddMessage: "&7%player% has been granted 'owner' for dimension %dimension%"
recvOwnerAddMessage: "&7You have been granted 'owner' for dimension %dimension%"
sendOwnerRemoveMessage: "&7%player has been revoked 'owner' for dimension %dimension%"
recvOwnerRemoveMessage: "&7You have been revoked 'owner' for dimension %dimension%"
sendMemberAddMessage: "&7%player% has been granted 'member' for dimension %dimension%"
recvMemberAddMessage: "&7You have been granted 'member' for dimension %dimension%"
sendMemberRemoveMessage: "&7%player has been revoked 'member' for dimension %dimension%"
recvMemberRemoveMessage: "&7You have been revoked 'member' for dimension %dimension%"
sendKickMessage: "&7%player% has been kicked from dimension %dimension%"
recvKickMessage: "&7You have been kicked from dimension %dimension%"

###################################
#####       No Touchie        #####
###################################
dontTouch:
  version:
    seriouslyThisWillEraseYourConfig: 1.0