###################################
#####  MystcraftUtils Config  #####
###################################

# World that players spawn in. This will be the same as the world location in server.properties
spawnWorld: "world"

# Dimensions that players cannot claim and will not be auto-teleported in
blacklistedDimensions:
  - "world"
  - "world_the_nether" # Vanilla *sigh*
  - "world_the_end" # Vanilla *sigh*
  - "DIM1" # End
  - "DIM-1" # Nether
  - "DIM2" #  SpectreWorld
  - "DIM3" # Compact Machines
  - "DIM69" # Pocket Plane Dimension
  - "DIM-19" # Thaumic Tinkerer Bedrock Dimension
  - "DIM-28" # Galacticraft Moon
  - "DIM-29" # Galacticraft Mars
  - "DIM-30" # Galacticraft Asteroids Dimension
  - "DIM-38" # Witchery Torment World
  - "DIM-39" # Witchery Mirror World
  - "DIM-42" # Thaumcraft The Outer Lands
  - "DIM-100" # Extra Utilities Deep Dark
  - "DIM-112" # Extra Utilities The Last Milennium
  - "DIM9" # Custom stuffs
  - "DIM16" # Custom stuffs
  - "Overworld" # *sigh*
  - "PP_Overworld" # Why do you do this
  - "DW20_Overworld" # I thought you learned from the Infinity-1 incident
  - "Infinity_Overworld" # But noooo....
  - "Lobby_Overworld" # You just had to keep on naming things weirdly.
  - "AS2_Overworld" # I really dont see the point of this

# Whether players will get auto-teleported to spawn on logout
autoSpawnLogin: true
autoSpawnLogout: true

###################################
#####         Events          #####
###################################
# Usable variables are %dimension% and %player%

# Executing as console solves some permission issues and keeps the player from recieving unwanted spam
executeCommandsAsConsole: true
# Sends you a message containing the command executed.
debugCommands: false

# Called when someone claims a dimension
claim:
  messages:
    success: "&7You have successfully claimed dimension &6%dimension%"
    alreadyClaimed: "&7Dimension &6%dimension%&7 is already claimed by &6%player%"
  commands:
    - "/rg addowner -w %dimension% __global__ %player%"
    - "/rg flag -w %dimension% __global__ passthrough DENY"
    - "/rg flag -w %dimension% __global__ build DENY"
    - "/rg flag -w %dimension% __global__ interact DENY"
    - "/rg flag -w %dimension% __global__ entry-deny-message This dimension has been claimed by %player%"

# Called when a claim (and the dimension along with it) is deleted
delete:
  # Number of letters of the UID a player must enter before they can delete a world. The longer the less chance of accidential deletion
  uidchars: 8
  messages:
    success: "&7Dimension &6%dimension%&7 has been deleted"
    confirm: "&eWARNING: &cYou are about to delete this age. Type\n'/myst delete confirm <age_name> %uid%' to delete this age."
  commands:
    - "/rg removeowner -w %dimension% __global__ -a"
    - "/rg removemember -w %dimension% __global__ -a"
    - "/rg flag -w %dimension% __global__ passthrough"
    - "/rg flag -w %dimension% __global__ build"
    - "/rg flag -w %dimension% __global__ interact"
    - "/rg flag -w %dimension% __global__ entry-deny-message"

# Called when an owner is added to a dimension
addOwner:
  # Number of letters of the UID a player must type enter before they can add an owner.
  uidchars: 6
  messages:
    toSender: "&6%player% &7has been granted '&6owner&7' for dimension &6%dimension%"
    toReceiver: "&7You have been granted '&6owner&7' for dimension &6%dimension%"
    alreadyOwner: "&6%player% &7is already an owner"
    alreadyMember: "&6%player% &7is already a member. Removing player as a member"
    alreadyOwnerOtherDim: "&6%player% &7has exceeded their maximum number of dimensions. Cannot promote to owner"
    confirm: "&eWARNING: &cOwners have the ability to delete ages. Type\n'/myst addowner <player> confirm <age_name> %uid%' to add an owner."
  commands:
    - "/rg addowner -w %dimension% __global__ %player%"

# Called when an owner is removed from a dimension
removeOwner:
  messages:
    success: "&7%player% &7has been revoked '&6owner&7' for dimension &6%dimension%"
    notFound: "&6%player% &7is not an owner"
  commands:
    - "/rg removeowner -w %dimension% __global__ %player%"

# Called when a member is added to a dimension
addMember:
  messages:
    toSender: "&6%player% &7has been granted '&6member&7' for dimension &6%dimension%"
    toReceiver: "&7You have been granted '&6member&7' for dimension &6%dimension%"
    alreadyOwner: "&6%player% &7is already an owner"
    alreadyMember: "&6%player% &7is already a member"
  commands:
    - "/rg addmember -w %dimension% __global__ %player%"

# Called when a member is removed from a dimension
removeMember:
  messages:
    success: "&6%player% &7has been revoked '&6member&7' for dimension &6%dimension%"
    notFound: "&6%player% &7is not a member"
  commands:
    - "/rg removemember -w %dimension% __global__ %player%"

# Called when a player is kicked from a dimension
# %player% in this case is the player being kicked
kick:
  messages:
    toSender: "&6%player% &7has been kicked from dimension &6%dimension%"
    toReceiver: "&7You have been kicked from dimension &6%dimension%"
  commands: []

###################################
#####      Misc Messages      #####
###################################

noPermission: "&4ERR: &cYou don't have permission"
noDimPermission: "&4ERR: &cYou don't have permission in this dimension"
noConsoleMessage: "&4ERR: &cOnly players can preform this command"
invalidWorld: "&4ERR: &cThe specified world &6%dimension% &cis invalid"
dimensionMaxExceeded: "&4ERR: &cYou have exceeded your maximum number of dimensions"
playerNotFound: "&4ERR: &cThe specified player could not be found"
errSelf: "&4ERR: &cYou cannot preform this action on yourself"
blacklistMessage: "&eWARNING: &7Blacklisted dimension. Event cancelled"
notRegisteredMessage: "&7The dimension &6%dimension% &7is not registered. Have you tried claiming it?"
teleportSuccess: "&7You have been teleported to dimension &6%dimension%"

###################################
#####       No Touchie        #####
###################################
dontTouch:
  version:
    seriouslyThisWillEraseYourConfig: 1.0
