###################################
#####  MystcraftUtils Config  #####
###################################

# World that players spawn in. Most often the overworld
spawnWorld: "LandOfWarfare"

# Dimensions that players cannot claim and will not be auto-teleported in
blacklistedDimensions:
 - "Overworld"
 - "Overworld_the_End"
 - "LandOfWarfare"

# Whether players will get auto-teleported to spawn on logout
autoSpawnLogin: false
autoSpawnLogout: true

###################################
#####         Events          #####
###################################

# Called when someone claims a dimension
onClaim:
  - "/rg -w %dimension% addowner __global__ %player%"
  - "/rg -w %dimension% flag __global__ entry DENY"
  - "/rg -w %dimension% flag __global__ entry-deny-message This dimension has been claimed by %player%"

# Called when an owner is added to a dimension
onAddOwner:
  - "/rg -w %dimension% addowner __global__ %player%"

# Called when an owner is removed from a dimension
onRemoveOwner:
  - "/rg -w %dimension% removeowner __global__ %player%"

# Called when a member is added to a dimension
onAddMember:
  - "/rg -w %dimension% addmember __global__ %player%"

# Called when a member is removed from a dimension
onRemoveMember:
  - "/rg -w %dimension% removemember __global__ %player%"

###################################
#####        Messages         #####
###################################

noPermission: "&cYou don't have permission"

idMessage: "&7Dimension name: &6%dimension%"
claimMessage: "&7You have successfully claimed dimension &6%dimension%"
alreadyClaimedMessage: "&7Dimension %dimension% is already claimed by %player%"
deleteMessage: "&7Dimension &6%dimension%&6 has been deleted"
spawnMessage: "&7You have been sent to spawn from %dimension%"
blacklistMessage: "&7Blacklisted dimension. Event cancelled"
reloadMessage: "&7Config has been reloaded"
noConsoleMessage: "&7Only players can preform this command"
notRegisteredMessage: "&7The dimension &6%dimension% &7is not registered"

sendOwnerAddMessage: "&6%player% &7has been granted '&6owner&7' for dimension &6%dimension%"
recvOwnerAddMessage: "&7You have been granted '&6owner&7' for dimension &6%dimension%"
sendOwnerRemoveMessage: "&7%player has been revoked '&6owner&7' for dimension &6%dimension%"
recvOwnerRemoveMessage: "&7You have been revoked '&6owner&7' for dimension &6%dimension%"
sendMemberAddMessage: "&6%player% &7has been granted '&6member&7' for dimension &6%dimension%"
recvMemberAddMessage: "&7You have been granted '&6member&7' for dimension &6%dimension%"
sendMemberRemoveMessage: "&6%player% &7has been revoked '&6member&7' for dimension &6%dimension%"
recvMemberRemoveMessage: "&7You have been revoked '&6member&7' for dimension &6%dimension%"
sendKickMessage: "&6%player% &7has been kicked from dimension &6%dimension%"
recvKickMessage: "&7You have been kicked from dimension &6%dimension%"

###################################
#####       No Touchie        #####
###################################
dontTouch:
  version:
    seriouslyThisWillEraseYourConfig: 1.0
