###################################
#####  MystcraftUtils Config  #####
###################################

# World that players spawn in. Most often the overworld
spawnWorld: "world"

# Dimensions that players cannot claim and will not be auto-teleported in
blacklistedDimensions:
 - "world"
 - "Overworld"
 - "DIM1"

# Whether players will get auto-teleported to spawn on logout
autoSpawnLogin: true
autoSpawnLogout: true

###################################
#####         Events          #####
###################################
# Usable variables are %dimension% and %player%

# Executing as console solves some permission issues and keeps the player from recieving unwanted spam
executeCommandsAsConsole: true
# Sends you a message containing the command executed.
debugCommands: false

# Called when someone claims a dimension
claim:
  messages:
    success: "&7You have successfully claimed dimension &6%dimension%"
    alreadyClaimed: "&7Dimension &6%dimension%&7 is already claimed by %player%"
  commands:
    - "/rg addowner -w %dimension% __global__ %player%"
    - "/rg flag -w %dimension% __global__ passthrough DENY"
    - "/rg flag -w %dimension% __global__ build DENY"
    - "/rg flag -w %dimension% __global__ interact DENY"
    - "/rg flag -w %dimension% __global__ entry-deny-message This dimension has been claimed by %player%"

# Called when a claim (and the dimension along with it) is deleted
delete:
  messages:
    success: "&7Dimension &6%dimension%&7 has been deleted"
  commands:
    - "/rg removeowner -w %dimension% __global__ -a"
    - "/rg removemember -w %dimension% __global__ -a"

# Called when an owner is added to a dimension
addOwner:
  messages:
    toSender: "&6%player% &7has been granted '&6owner&7' for dimension &6%dimension%"
    toReceiver: "&7You have been granted '&6owner&7' for dimension &6%dimension%"
    alreadyOwner: "&6%player% &7is already an owner"
  commands:
    - "/rg addowner -w %dimension% __global__ %player%"

# Called when an owner is removed from a dimension
removeOwner:
  messages:
    toSender: "&7%player has been revoked '&6owner&7' for dimension &6%dimension%"
    tpReceiver: "&7You have been revoked '&6owner&7' for dimension &6%dimension%"
    notFound: "&6%player% &7is not an owner"
  commands:
    - "/rg removeowner -w %dimension% __global__ %player%"

# Called when a member is added to a dimension
addMember:
  messages:
    toSender: "&6%player% &7has been granted '&6member&7' for dimension &6%dimension%"
    toReceiver: "&7You have been granted '&6member&7' for dimension &6%dimension%"
    alreadyOwner: "&6%player% &7is already an owner"
    alreadyMember: "&6%player% &7is already a member"
  commands:
    - "/rg addmember -w %dimension% __global__ %player%"

# Called when a member is removed from a dimension
removeMember:
  messages:
    toSender: "&6%player% &7has been revoked '&6member&7' for dimension &6%dimension%"
    toReceiver: "&7You have been revoked '&6member&7' for dimension &6%dimension%"
    notFound: "&6%player% &7is not a member"
  commands:
    - "/rg removemember -w %dimension% __global__ %player%"

# Called when a player is kicked from a dimension
# %player% in this case is the player being kicked
kick:
  messages:
    toSender: "&6%player% &7has been kicked from dimension &6%dimension%"
    toReceiver: "&7You have been kicked from dimension &6%dimension%"
  commands: []

###################################
#####      Misc Messages      #####
###################################

noPermission: "&4ERR: &cYou don't have permission to execute this command"
noDimPermission: "&4ERR: &cYou don't have permission in this dimension"
noConsoleMessage: "&4ERR: &cOnly players can preform this command"
invalidWorld: "&4ERR: &cThe specified world &6%dimension% &cis invalid"
playerNotFound: "&4ERR: &cThe specified player could not be found"
blacklistMessage: "&eWARNING: &7Blacklisted dimension. Event cancelled"
notRegisteredMessage: "&7The dimension &6%dimension% &7is not registered"
teleportSuccess: "&7You have been teleported to dimension &6%dimension%"

###################################
#####       No Touchie        #####
###################################
dontTouch:
  manualConfigReset: false
  version:
    seriouslyThisWillEraseYourConfig: 1.0
