name: DimensionGuard
main: net.willsr71.dimensionguard.DimensionGuard
version: 1.0
description: The ultimate dimension and mystcraft age manager.
author: Willsr71
website: http://willsr71.net/
commands:
  dg:
    description: Core command for DimensionGuard
    usage: /dg
    aliases: [dimensionguard]
  dgclaim:
    usage: /dg claim
  dgdelete:
    usage: /dg delete
  dginfo:
    usage: /dg info
  dgkick:
    usage: /dg kick <player>
  dglist:
    usage: /dg list
  dglistown:
    usage: /dg listown
  dgspawn:
    usage: /dg spawn
  dgtpx:
    usage: /dg tpx <dimension>
  dgaddowner:
    usage: /dg addowner <player>
  dgaddmember:
    usage: /dg addmember <player>
  dgremoveowner:
    usage: /dg removeowner <player>
  dgremovemember:
    usage: /dg removemember <player>
  dgreload:
    usage: /dg reload
permissions:
  dgcraftutils.*:
    default: op
    description: Give access to all of everything
    children:
      dgcraftutils.overrideowner: true
      dgcraftutils.overridemember: false
      dgcraftutils.reload: true
      dgcraftutils.tpx: true
      dgcraftutils.tp.others: true
      dgcraftutils.kick: true
  dgcraftutils.overrideowner:
    default: op
    description: Override dimension owner
  dgcraftutils.overridemember:
    default: false
    description: Override dimension member
  dgcraftutils.reload:
    desfault: op
    description: The ability to reload plugin configs
  dgcraft.tpx:
      default: op
      description: The ability to teleport to dimensions
  dgcraftutils.tp.others:
    default: op
    description: The ability to teleport others to spawn
  dgcraft.kick:
    default: op
    description: The ability to kick players from a dimension
